# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True, verbose_name='关键词')),
                ('enable', models.IntegerField(default=1, verbose_name='是否启用')),
                ('DATECREATED', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('DATEMODIFED', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('DELETED', models.BooleanField(default=True, verbose_name='是否删除')),
                ('ENTITY_NAME', models.CharField(max_length=255, null=True, verbose_name='实体名')),
            ],
            options={
                'verbose_name_plural': '关键词',
                'db_table': 'keywords',
                'verbose_name': '关键词',
            },
        ),
        migrations.CreateModel(
            name='LoginInFo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('enable', models.IntegerField(default=1, verbose_name='是否启用')),
                ('DATECREATED', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('DATEMODIFED', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('DELETED', models.BooleanField(default=True, verbose_name='是否删除')),
                ('ENTITY_NAME', models.CharField(max_length=255, null=True, verbose_name='实体名')),
            ],
            options={
                'verbose_name_plural': '微博登陆账号',
                'db_table': 'login_info',
                'verbose_name': '微博登陆账号',
            },
        ),
        migrations.CreateModel(
            name='Save2kafkalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.CharField(max_length=20, verbose_name='微博发布时间')),
                ('lastWeiboId', models.CharField(max_length=255, verbose_name='最后一个微博ID')),
                ('longCreateTime', models.BigIntegerField(verbose_name='微博发布时间Long')),
                ('spiderTime', models.DateTimeField(verbose_name='采集时间')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('uid', models.CharField(max_length=255, verbose_name='最后一个用户ID')),
                ('lastId', models.IntegerField(verbose_name='采集截止的数据')),
            ],
            options={
                'verbose_name_plural': '保存kafka日志',
                'db_table': 'save2kafkalog',
                'verbose_name': '保存kafka日志',
            },
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='用户ID')),
                ('is_crawled', models.IntegerField(default=0, verbose_name='是否采集')),
                ('other_crawled', models.IntegerField(default=0, verbose_name='是否采集粉丝')),
                ('home_crawled', models.IntegerField(default=0, verbose_name='是否过主页')),
                ('DATECREATED', models.DateTimeField(verbose_name='创建时间')),
                ('DATEMODIFED', models.DateTimeField(verbose_name='修改时间')),
                ('DELETED', models.BooleanField(default=True, verbose_name='是否删除')),
                ('ENTITY_NAME', models.CharField(max_length=255, verbose_name='实体名')),
            ],
            options={
                'verbose_name_plural': '要采集的账号',
                'db_table': 'seed_ids',
                'verbose_name': '要采集的账号',
            },
        ),
        migrations.CreateModel(
            name='WbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='用户ID')),
                ('name', models.CharField(max_length=200, verbose_name='昵称')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('birthday', models.CharField(max_length=200, verbose_name='生日')),
                ('location', models.CharField(max_length=100, verbose_name='地域信息')),
                ('description', models.CharField(max_length=500, verbose_name='简介')),
                ('register_time', models.CharField(max_length=200, verbose_name='注册时间')),
                ('verify_type', models.IntegerField(default=0, verbose_name='认证')),
                ('follows_num', models.IntegerField(default=0, verbose_name='关注数')),
                ('fans_num', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('wb_num', models.IntegerField(default=0, verbose_name='微博数')),
                ('level', models.IntegerField(default=0, verbose_name='级别')),
                ('tags', models.CharField(max_length=500, verbose_name='标签')),
                ('contact_info', models.CharField(max_length=300, verbose_name='联系信息')),
                ('education_info', models.CharField(max_length=300, verbose_name='教育信息')),
                ('head_img', models.CharField(max_length=500, verbose_name='头像地址')),
                ('work_info', models.CharField(max_length=500, verbose_name='工作信息')),
                ('verify_info', models.CharField(max_length=300, verbose_name='认证信息')),
            ],
            options={
                'verbose_name_plural': '微博用户信息',
                'db_table': 'wbuser',
                'verbose_name': '微博用户信息',
            },
        ),
        migrations.CreateModel(
            name='WeiboData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.CharField(max_length=20, unique=True, verbose_name='微博ID')),
                ('weibo_cont', models.TextField(verbose_name='内容')),
                ('repost_num', models.IntegerField(default=0, verbose_name='回复数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('praise_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('uid', models.CharField(max_length=20, verbose_name='用户Id')),
                ('is_origin', models.IntegerField(default=1, verbose_name='是否为源微博')),
                ('device', models.CharField(max_length=200, verbose_name='发布设备')),
                ('weibo_url', models.CharField(max_length=300, verbose_name='URL')),
                ('create_time', models.CharField(max_length=200, verbose_name='发布时间')),
                ('comment_crawled', models.IntegerField(default=0, verbose_name='是否抓取评论')),
                ('repost_crawled', models.IntegerField(default=0, verbose_name='回复是否抓取')),
            ],
            options={
                'verbose_name_plural': '微博信息',
                'db_table': 'weibo_data',
                'verbose_name': '微博信息',
            },
        ),
    ]
